version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: chat-app-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: chatapp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - chat-app-network

  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chat-app-backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/chatapp?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - chat-app-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend/chat_app_fronend
      dockerfile: Dockerfile
    container_name: chat-app-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chat-app-network

  # Development Frontend (for development mode)
  frontend-dev:
    build:
      context: ./frontend/chat_app_fronend
      dockerfile: Dockerfile.dev
    container_name: chat-app-frontend-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5001
    depends_on:
      - backend
    volumes:
      - ./frontend/chat_app_fronend:/app
      - /app/node_modules
    networks:
      - chat-app-network
    profiles:
      - dev

volumes:
  mongodb_data:
    driver: local

networks:
  chat-app-network:
    driver: bridge