services:
  - type: web
    name: chat-app-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: STREAM_API_KEY
        sync: false
      - key: STREAM_API_SECRET
        sync: false
      - key: JWT_SECRET_KEY
        sync: false

  - type: static
    name: chat-app-frontend
    buildCommand: cd frontend/chat_app_fronend && npm install && npm run build
    staticPublishPath: frontend/chat_app_fronend/dist
    envVars:
      - key: VITE_STREAM_API_KEY
        sync: false
      - key: VITE_API_URL
        value: https://chat-app-backend.onrender.com