services:
  - type: web
    name: chat-app-backend
    env: node
    plan: free
    root: ./backend
    buildCommand: npm install
    startCommand: npm start
    dockerfilePath: ""
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: STREAM_API_KEY
        sync: false
      - key: STREAM_API_SECRET
        sync: false
      - key: JWT_SECRET_KEY
        sync: false

  - type: web
    name: chat-app-frontend
    env: static
    plan: free
    root: ./frontend/chat_app_fronend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    dockerfilePath: ""
    envVars:
      - key: VITE_STREAM_API_KEY
        sync: false
      - key: VITE_API_URL
        value: https://chat-app-backend.onrender.com